### ISSUE TITLE
Integration with Redux-persist

### ISSUE THREAD

**Issue by pongponglau** [rauliyohmc/react-native-offline#22]
Thank you so much for this great library. It gives me (a newbie to react-native) a great help in developing an app that works in offline mode using react-native. May i ask if i can add Redux-persist on top of  your library by doing something like the following?  Thank you so much for your advice. 

const store = createStore(
  rootReducer,
compose(
  applyMiddleware([networkMiddleware, thunk]),
    autoRehydrate()
  )
);

persistStore(store, { storage: AsyncStorage });

**Comment by rauliyohmc** [comment]
Absolutely! That will work as expected. The only thing to notice is that if you want to persist also the offline state, you need to add the `network` reducer to your `rootReducer`. You can take a look in [here](https://github.com/rauliyohmc/react-native-offline#usage-2)

**Comment by pongponglau** [comment]
Thanks a lot
