### ISSUE TITLE
How to use the library with Redux Thunk and Redux Persist

### ISSUE THREAD

**Issue by jchesne** [rauliyohmc/react-native-offline#23]
Hello,

It would be really apreciated if you could show us an exemple on how to use your usefull library with Redux Thunk and Redux Persist.
I tried to do it without success. How do we have to initialise the middleware ?

I have anything like this : 

```
import {persistStore, autoRehydrate} from "redux-persist";
import {applyMiddleware, createStore, compose} from "redux";
import {AsyncStorage} from "react-native";
import thunk from "redux-thunk";
import reducers from './reducers';

import {createNetworkMiddleware} from 'react-native-offline';

const middlewares = [thunk,createNetworkMiddleware];


store = createStore(reducers, undefined, compose(
        applyMiddleware(...middlewares),
        autoRehydrate()
    ));


persistStore(store, {storage: AsyncStorage});

export default store;

```
Thanks in advance, and good job for the library.

**Comment by rauliyohmc** [comment]
`createNetworkMiddleware` should be the first middleware in the chain. Try changing the order such as:

`const middlewares = [createNetworkMiddleware, thunk];`

It's actually stated [here in the docs](https://github.com/rauliyohmc/react-native-offline#usage-3) :)

**Comment by jchesne** [comment]
Oh yes, now my application is loading, thanks !

But, i think i fully misunderstand how does the library work with standard architecture like this : 

My component : 

```
import {fetchUsers} from './../actions';
...
componentWillUnmount() {
        this.props.fetchUsers();
}
...
export default connect(mapStateToProps, {
    fetchUsers
})(FirstScreenLoader);
```

My action : 

```
export const fetchUser = () => {
    return (dispatch) => {
        fetch(url_api)
            .then((response) => response.json())
            .then((responseJson) => {
                dispatch({type: INIT_ALL_USER_DATAS_SUCCESS, payload: responseJson});
            })
            .catch((error) => {
                console.error(error);
            });
    };
};
```
At this stage, i dont know how does the library can intercept my fetch call, do i miss something ?

**Comment by rauliyohmc** [comment]
You are right. For thunks it's not that trivial and I just realised about it. There is a workaround for your code though.

The problem is that the library currently relies on the function _returned_ name, rather than in the thunk name (I should state that clearer in the docs).

You'd have to tweak your action in the next way:

```javascript
export const fetchUser = () => {
    return function fetchData(dispatch) {
        fetch(url_api)
            .then((response) => response.json())
            .then((responseJson) => {
                dispatch({type: INIT_ALL_USER_DATAS_SUCCESS, payload: responseJson});
            })
            .catch((error) => {
                console.error(error);
            });
    };
};
```

I'll update the docs and the article. I still think it's a valid solution and doesn't require too much changes in an existing codebase, just replacing anonymous functions with named ones, despite the fact that adds a bit of redundancy.

Thanks a lot for your input!

**Comment by jchesne** [comment]
Thanks Raul, its working now !

**Comment by pongponglau** [comment]
I have an app with a flatlist UI using thunk. I want to add offline capability to this flatlist with react-native-offline library. I test the app in an ios simulator running in macbook air. I simulate the network conditions by on/off the wifi connection of macbook air.


I encounter 2 issues:

1) when i turn off the wifi, offlineActionTypes.CONNECTION_CHANGE is captured by my reducer every time. However, the same event is not reliably captured (cannot capture most of the time) when i turn on the wifi again (same to offlineActionTypes.FETCH_OFFLINE_MODE). 

2) the thunk return function is not called most of the time when wifi is back. When it is called, it is called twice

Thank you very much for your advices.

**Comment by rauliyohmc** [comment]
I am aware of the 1st issue and I believe the 2nd is related to the 1st. That's a specific problem of the iOS simulator, since it works fine in real devices. Please follow this thread for further updates:
https://github.com/rauliyohmc/react-native-offline/issues/10

**Comment by Milankorangi** [comment]
> I have an app with a flatlist UI using thunk. I want to add offline capability to this flatlist with react-native-offline library. I test the app in an ios simulator running in macbook air. I simulate the network conditions by on/off the wifi connection of macbook air.
> 
> I encounter 2 issues:
> 
> 1. when i turn off the wifi, offlineActionTypes.CONNECTION_CHANGE is captured by my reducer every time. However, the same event is not reliably captured (cannot capture most of the time) when i turn on the wifi again (same to offlineActionTypes.FETCH_OFFLINE_MODE).
> 2. the thunk return function is not called most of the time when wifi is back. When it is called, it is called twice
> 
> Thank you very much for your advices.

can you help with react-native offline

**Comment by Milankorangi** [comment]
could you please help me with react-native-offline

**Comment by fadinasr** [comment]
@rgommezz Hello Raul, I tried applying the workarounds mentioned in the issue and in the official documentation (transforms with thunks that has meta) and I'm still facing null actions added to the actionQueue. Any help on that?
