### ISSUE TITLE
redux-thunk and react-native-offline setup

### ISSUE THREAD

**Issue by arribbar** [rauliyohmc/react-native-offline#30]
In the readme, we have
```
import { createStore, applyMiddleware } from 'redux';
import { createNetworkMiddleware } from 'react-native-offline';
import createSagaMiddleware from 'redux-saga';

const sagaMiddleware = createSagaMiddleware();
const networkMiddleware = createNetworkMiddleware();

const store = createStore(
  rootReducer,
  applyMiddleware([networkMiddleware, sagaMiddleware])
);
```

I do not know if it is the same for sagaMiddleware but for redux-thunk, we need to use `applyMiddleware` without an array like:
```
const store = createStore(
  rootReducer,
  applyMiddleware(networkMiddleware, thunk)
);
```
So, question, is it the readme which is not up to date or it is just redux-thunk working differently ?(or it is only just for me ^^)

**Comment by adrienthiery** [comment]
Hi @arribbar ,

I'm pretty sure it is supposed to be `applyMiddleware(...[networkMiddleware, sagaMiddleware])` instead of `applyMiddleware([networkMiddleware, sagaMiddleware])`, so it is the README that has a typo.

In my case, I use it with `Thunk` and it works like a charm that way : 
```
applyMiddleware(...[
        networkMiddleware,
        Thunk,
]),
```

**Comment by arribbar** [comment]
Thanks @adrienthiery  :)
