### ISSUE TITLE
Testing offline behavior while actually online

### ISSUE THREAD

**Issue by smoll** [rauliyohmc/react-native-offline#31]
I've been using this with a Redux-connected component as described in https://github.com/rauliyohmc/react-native-offline#integration-with-redux and it's been great so far, however, one thing I'd like to do is be able to test the "offline behavior" while not actually in airplane mode.

Is it possible to introduce a boolean flag, for use in Dev only, that will allow me to do this? In other words: where would I be able to hook into this library, preferably in a single place, that will allow me to override `isConnected` to be `true`/`false` using an env var?

**Comment by fredbt** [comment]
This is a good thing. So far it's unclear how to test it. In the emulator, if I turn the connection off via airplane mode, I cannot connect to the remote debugger and log stuff. It would be cool if we could simulate the offline behavior while still connecting to the remote debugger.

**Comment by adrienthiery** [comment]
Hi guys,

I think you could add the `pingServerUrl` as described in the `README` : 
```
2.- Wrap your top most React component into withNetworkConnectivity and configure it with withRedux = true.

The other config parameters, timeout and pingServerUrl can be provided to the store as well. Make sure your component is a descendant of the react-redux <Provider> component, so that withNetworkConnectivity has access to the store.
```
Then you can either take your dev server down, or put a "Bad" pingUrl to try the offline behaviour ?

**Comment by smoll** [comment]
@adrienthiery don't know how I missed that. This works perfectly for my use case 👍

**Comment by LaloHao** [comment]
Is it possible to configure the url with an action/reducer? 
Right now the app needs to be reloaded entirely to change the url
