### ISSUE TITLE
Native error on disabling wifi and enabling back

### ISSUE THREAD

**Issue by lucasbento** [rauliyohmc/react-native-offline#34]
When I disable wifi it works fine, the `isConnected` property is updated and everything, when I enable it back the app freezes and shows this error on Xcode:

![image](https://user-images.githubusercontent.com/6207220/29866313-59577770-8d78-11e7-92f6-1b49fb52e28c.png)

This doesn't happen every time, sometimes it works enabling it back but then crashes when I disable and enable again.

I'm not sure if this a react-native-offline-related issue, it seems to happen with react-native's `NetInfo` as well, everything works fine if I simulate updating `isConnected` property on the store with a `setInterval` function.

---

# Code

<details>
 <summary>reducers/index.js</summary>

```js
import { reducer as network } from 'react-native-offline';

// ...

export default combineReducers({
  // ...
  network,
});
```
</details>

<details>
 <summary>Main.js (top component)</summary>

```js
import { withNetworkConnectivity } from 'react-native-offline';

class Main extends Component {
  // ...
} 

export default withNetworkConnectivity({
  withRedux: true,
})(connect(mapStateToProps, mapDispatchToProps)(Main));
```
</details>

<details>
 <summary>MyComponent.js (component I'm using `isConnected`)</summary>

```js
class MyComponent extends Component {
  render() {
    if (this.props.network.isConnected) {
      return (
        <View>
          <Text>Not connected</Text>
        </View>
      );
    }

    return (
        <View>
          <Text>My awesome view</Text>
        </View>
    );
  }
}

const mapStateToProps = ({ network }) => ({
  network,
});

export default connect(mapStateToProps)(MyComponent);
```
</details>

---

# Versions

- **maxOS**: Sierra `10.12.6`
- **iOS**: `10.3.3`
- **react-native**: `0.47.2`
- **react-native-offline**: `3.1.0`

**Comment by guilhermepontes** [comment]
+1

**Comment by lucasbento** [comment]
Apparently it was some sort of bug with `react-native-maps` using `GoogleMaps` on iOS, updating it from `2.1.1` to `2.4.0` solved it.

![idk-jim-carrey-shrug-w0mylo7p4OXUQ](https://media1.giphy.com/media/w0mylo7p4OXUQ/giphy.gif?fingerprint=e1bb72ff59a7e7fb42414d6e4571d577)
