### ISSUE TITLE
NetInfo Event change deprecated

### ISSUE THREAD

**Issue by malikoum94** [rauliyohmc/react-native-offline#36]
hi,

your event listener `NetInfo.isConnected.addEventListener('change', this.checkInternet)` is deprecated will you update the module for fix this?

thanks

**Comment by Krizzu** [comment]
Hey @malikoum94, thanks for Your input!
We're open to help with the library! Feel free to send a PR :)

**Comment by gtfargo** [comment]
@Krizzu here ya go https://github.com/rauliyohmc/react-native-offline/pull/37
