### ISSUE TITLE
[Question] Delay actions to be dispatched after CONNECTION_CHANGED is dispatched

### ISSUE THREAD

**Issue by peterdev6** [rauliyohmc/react-native-offline#42]
Is there any way of delaying all redux actions to be dispatched until __offlineActionTypes.CONNECTION_CHANGE__ action is fired?

Reason being that right now the initial state of the network.isConnected is __true__ and this is an issue when users open apps with no internet connection

Thanks

**Comment by rauliyohmc** [comment]
That issue will be fixed soon, see [this](https://github.com/rauliyohmc/react-native-offline/issues/39#issuecomment-331304787) and [this](https://github.com/rauliyohmc/react-native-offline/pull/29#issuecomment-324948132) for related threads.

In the meantime, you can use `setTimeout` in your setup actions (if those are triggered within your components) or particular helpers that come shipped with middleware (like `delay` effect in redux saga)

**Comment by rauliyohmc** [comment]
I proposed a solution in here: https://github.com/rauliyohmc/react-native-offline/issues/39#issuecomment-333997252

I'll create soon a section in the readme to cover this case, so that others can refer to :)
