### ISSUE TITLE
NetInfo.isConnected eventlistener not properly removed on unmount

### ISSUE THREAD

**Issue by markvl91** [rauliyohmc/react-native-offline#50]
I've noticed the event listener on NetInfo.isConnected isn't getting removed properly. It seems this was introduced in **Added ability to check connectivity regularly (#32)**.

See:
```javascript
    componentDidMount() {
      NetInfo.isConnected.addEventListener(
        'connectionChange',
        withExtraHeadRequest ? this.checkInternet : this.handleNetInfoChange,
      );
    }
```

and

```javascript
    componentWillUnmount() {
      NetInfo.isConnected.removeEventListener(
        'connectionChange',
        withExtraHeadRequest
          ? this.handleNetInfoChange
          : this.handleConnectivityChange,
      );
    }
```

I'm assuming, based on the change, that the addEventListener should be using this.handleNetInfoChange and this.handleConnectivityChange, though I'm not familiar enough with the project to say that with full confidence.

**Comment by markvl91** [comment]
I've submitted a pull request (#51) based on my assumptions, in case they are correct.

**Comment by rauliyohmc** [comment]
Hey @markvl91, good catch. Your assumptions are correct. Just make sure CI passes and I'll merge it. Thanks!
