### ISSUE TITLE
Attempted to remove more RCTKeyboardObserver listeners than added

### ISSUE THREAD

**Issue by gitpayal** [rauliyohmc/react-native-offline#55]
I am using this library for displaying no connection screen on mobile. On iOS , I am getting red screen error when my keyboard is displaying on screen and I disconnect internet.

My configurations 
 "react-native": "^0.42.3",
"react-native-offline": "^3.4.1",

![image uploaded from ios](https://user-images.githubusercontent.com/11710326/33182845-d576429c-d075-11e7-8ec8-f8b2ec38dfe4.jpg)

I think that because componentWillUnmount is not called when this library calls no connection screen, this error comes. Can anyone help me to have workaround for same.

Can anyone please suggest me or help me how to resolve this issue

**Comment by rauliyohmc** [comment]
Hi @gitpayal,

It may be cause you are using an incompatible version of the library. For RN < 0.47 you should install the version `3.2.0`. It's stated here in the docs: https://github.com/rauliyohmc/react-native-offline#rn--v047-1.

Let me know if that solves the issue

**Comment by gitpayal** [comment]
Dear @rauliyohmc ,

Thank you for reaching out. In my react-native app, instead of using 
Keyboard.removeAllListeners('keyboardWillShow')  for keyboard event, 
I changed it to Keyboard.removeListener('keyboardWillShow')  and the issue is gone. 

I think we can close this issue.
