### ISSUE TITLE
withNetworkConnectivity makes componentDidUpdate fire with initial render

### ISSUE THREAD

**Issue by MrHubble** [rauliyohmc/react-native-offline#56]
According to the React docs:

>componentDidUpdate() is invoked immediately after updating occurs. **This method is not called for the initial render.**

https://reactjs.org/docs/react-component.html#componentdidupdate

However, when I use `export default withNetworkConnectivity()(YourComponent)`, the `componentDidUpdate()` event is called even though I'm not changing state nor am I changing my network connectivity status. If I remove `withNetworkConnectivity` then `componentDidUpdate` is no longer called.

Is this expected behaviour?

[This](https://github.com/rauliyohmc/react-native-offline/issues/39#issuecomment-331304787) discussion may be relevant:

>withNetworkConnectivity HoC subscribes to connectivity change events after the component that it wraps mounts. Being that component the top most component, there is an implicit delay since React & RN have to render the whole app for the 1st time.

**Comment by rauliyohmc** [comment]
> Is this expected behaviour?

Yes, it could happen. You almost got to the point in the paragraph you quoted at the end. The component that `withNetworkConnectivity` wraps it first mounts and right after that it subscribes to connectivity events. It always performs an initial check to detect initial connectivity, calling `setState` internally. That causes your component to re-render, hence executing `componentDidUpdate` afterwards.

Even though the prop `isConnected` that gets injected to your component may not change, I think React will call the lifecycle method if you don't put into place any optimisations such as using a `PureComponent` or leveraging `shouldComponentUpdate` hook.
