### ISSUE TITLE
Being able to target which thunk to intercept from config [question][feature?]

### ISSUE THREAD

**Issue by MehdiAlouafi** [rauliyohmc/react-native-offline#65]
Hi there,

First of all : great lib, came at the right moment and is really straightforward and great ! 

I want to discuss the possibility to be able, from the `createNetworkMiddleware` function, to configure the thunk-actions to be retry

I wanted to discuss that because actually my implementation looks like this : 

- I have a bunch of thunk actions (a lot actually) that I transformed into a named function with name pattern that ends with Thunk

```
export const loadAllOtopsFromMyCommunity = () => {
    function loadAllOtopsFromMyCommunityThunk(dispatch, getState) {
        dispatch({ type: types.FETCH_REQUEST });
        const options = { /* ...*/ };

        fetch(`${URL}/api/otops/getfriendsotops`, options)
            .then(res => res.json())
            .then(otops => dispatch({
                type: types.FETCH_REQUEST_SUCCESS,
                payload: otops
            })).catch(err => dispatch({
                type: types.FETCH_REQUEST_FAILURE,
                error: err
            }));
    }
    return loadAllOtopsFromMyCommunityThunk;
};
```
And then I created a middleware : interceptInOfflineEveryThunkAction which looks like this : 
```
const interceptInOfflineEveryThunkAction = store => next => action => {

    if (action == null) {
        return null;
    }
    if (typeof action === 'function') {
        const thunkActionsToRetry = [
            'loadSomethingThunk',
            'fetchUserDataThunk',
        ];

        thunkActionsToRetry.forEach(thunkName => {
            if (thunkName === action.name) {
                action.meta = { retry: true };
            }
        });

        action.interceptInOffline = true;
        return next(action);
    }
    return next(action);
};
```
And so that saved me the pain of having to put the <ThunkName>.meta = { retry: true }, and so I was wondering if you find useful to add a : 'thunkNameToRetry' property to the config object that will accept function names in order to do this during the createNetworkMiddleware() call

Really I don't know if this might be helpful, the implementation is newbie (so am I) so if it is out of context then fine haha

Thanks for the great work

**Comment by rauliyohmc** [comment]
Hi @MehdiAlouafi, thanks. I am glad it's useful for you :)

Regarding your enquiry, that was my intent at the beginning, being able to configure which thunks should be intercepted passing a config to `createNetworkMiddleware`.

However, that carried out a problem that prevented it from working on production and that's the fact that function names are transformed during minification, so the middleware can't rely on that. That was the reason of adding that 2nd approach, which I agree is not as nice as the 1st intent, but at the end of the day it does the job.

Feel free to check this thread for more insigths: https://github.com/rauliyohmc/react-native-offline/issues/26#issuecomment-317996892
