### ISSUE TITLE
Network isConnected only true 

### ISSUE THREAD

**Issue by StoneSILU** [rauliyohmc/react-native-offline#67]
Hi,
I'm using react-native-offline with redux, i followed all steps in the readme. I am using thunks like 
```
export const deleteMail = (mailIds) => {

   function doDeleteMail(dispatch) {
    dispatch(deleteMailRequest)
    const params = {
      path: 'emails/moveToTrash/',
      method: 'PUT',
      body: {
        "messageIds": mailIds      
      },
    }
    fetch(apiRequest(params))
    .then(response => {
      errorHandler(response, true)
      .then(() => dispatch(deleteMailSuccess))
      .catch(error => console.log(error))
    })
    .catch(error => dispatch(deleteMailFailure(error)))
  }
  
  doDeleteMail.meta = {
    retry: true
  }
  
  doDeleteMail.interceptInOffline = true;
  
  return doDeleteMail;
}
```
but even if i turn on the airplane mode, network.isConnected stay at true. I tried to change checkConnectionInterval in withNetworkConnectivity config but nothing change.

Do you see an error in my code? There is someone with same issue?
RN : 0.47.2
react-native-offline : 3.5.0
Testing on android device

**Comment by stephane-r** [comment]
+1

**Comment by Saraujoc92** [comment]
Did you find a fix? I find that my component props update correctly indicating the reducer is setup correctly, but the middleware does not detect the network changes.

**Comment by wliadmin** [comment]
+1
