### ISSUE TITLE
Module does not exist redux-saga/effects

### ISSUE THREAD

**Issue by Aidurber** [rauliyohmc/react-native-offline#70]
**Version:** 3.7.0

I've just tried to upgrade to 3.7.0, I received the: 
> Unable to resolve module `redux-saga/effects` from `<app path>/node_modules/react-native-offline/src/saga.js`: Module does not exist. 

Given the standard 3 options to fix: clear watchman, remove and reinstall node modules, reset metro bundler cache. 

None of the above worked. When looking at the redux-saga source code, under the effects directory, there is no module, it's just a package.json. I'm not sure if the issue is redux-saga or this library. 

Thoughts?

**Comment by rauliyohmc** [comment]
Hi @Aidurber,

I had `redux-saga` as a dev dependency instead of a normal dependency. I released version `3.7.1` with that change. Could you please give it a try and let me know?

**Comment by Aidurber** [comment]
@rauliyohmc Perfect :ok_hand:

Thanks for the quick resolution!

**Comment by MehdiAlouafi** [comment]
I had the same exact problem **today** and I had to install myself redux-saga in order to make it work on android (iOS was fine) @rgommezz
