### ISSUE TITLE
React Native - actionQueue not dispatching when reconnected to network

### ISSUE THREAD

**Issue by imartingraham** [rauliyohmc/react-native-offline#72]
I just started a new app and have been testing out `react-native-offline`.  I followed the instructions on the readme to get `redux`, `redux-saga`, and `react-native-offline` working together and  everything seems to be working correctly except that the `actionQueue` does not dispatch the actions when coming back online.

When I switch to airplane mode on my phone I can see the actions going into the `actionQueue`.  When I switch out of airplane mode I can see that the phone is connecting again but the `actionQueue` doesn't dispatch the actions in the queue. 

My app is using the following packages:
- react-native 0.52
- react-redux 5.0.6
- redux 3.7 .2
- redux-saga 0.16.0
- react-native-offline 3.7.1 

I tracked the issue down to the `handleConnectivityChange` function in `src/sagas.js`. 

```javascript
function* handleConnectivityChange(
  hasInternetAccess: boolean,
): Generator<*, *, *> {
  yield put(connectionChange(hasInternetAccess));
  const actionQueue = select(
    (state: { network: NetworkState }) => state.network.actionQueue,
  );

  if (hasInternetAccess && actionQueue.length > 0) {
    // eslint-disable-next-line
    for (const action of actionQueue) {
      yield put(action);
    }
  }
}
```

More specifically the `const actionQueue = select(...)` line.  I believe this line should be:
```javascript
const actionQueue = yield select(...)
```
Without the `yield` keyword it returns something that looks like a function instead of an array. This is the output in the Xcode console:
```javascript
SELECT: { selector: [Function], args: [] } }
```

When I add `yield` in front of the call to `select` everything works as expected.  

I can create a pull request for this but the readme mentioned creating an issue first.  If you'd like a PR just let me know.

Thanks!

**Comment by rauliyohmc** [comment]
Hi @imartingraham, that's a great catch! Thanks for taking your time on debugging.

I really appreciate you open up an issue on the first place, people normally don't do so despite the Readme ;)

It would be great if you could send a PR!

**Comment by imartingraham** [comment]
@rauliyohmc Just submitted the pull request. I forgot to mention it in the initially issue comment, but this package is really nice to work with! Thank you

**Comment by rauliyohmc** [comment]
New patch version released. Glad you find it useful!
