### ISSUE TITLE
NetInfo's "change" event is deprecated

### ISSUE THREAD

**Issue by Bonobomagno** [rauliyohmc/react-native-offline#77]
> NetInfo's "change" event is deprecated. Listen to the "connectionChange" event instead.

any plan about?

**Comment by rauliyohmc** [comment]
Sorry, my bad. My last pushed version to npm was `3.6.2` to cherry pick the changes from the latest PR merged and `npm` tagged it as `latest`. That version still uses `change` instead of `connectionChange`. That should be fixed now and when you do `npm install` or `yarn add`, you should get `3.7.3`
